### ISSUE TITLE
Not working at this time

### ISSUE THREAD

**Issue by javerleo** [milkycode/joomla_recaptcha_j15#3]
The plugin doesn't work anymore (as of october 2019). It seems like the Google URL or the API changed. 
There are a lot of old sites that need this plugin to avoid spamming. Hope the developer could check it soon.

**Comment by crysix** [comment]
We have some customers using this plugin and it still works on all sites. What error do you get?

**Comment by javerleo** [comment]
Downloaded again and now it works. My mistake. Sorry for the inconvenience. Great job for those that still need to support oudated Joomla installations.
